name: Erotica Magazine-How to Get Girls
favicon: null
layout_spectrum: 0.5345
typography_spectrum: 0.48724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
