name: Erotica Magazine-Pick Up Artist Interviews
favicon: null
layout_spectrum: 0.7331462698057294
typography_spectrum: 0.5312250026036054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0889673731289804
  lightness: 0.07225012872368097
  saturation: 0.4234761798288673
  rhythmicContrast: 0.038187554106116295
purpose: []
